### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gavr123456789** [frida/vala#2]
Can you explain what this fork is for?

**Comment by oleavr** [comment]
Hi @ricotz! :-)

(Thanks for maintaining Vala btw! ❤️)

This "fork" – along with libffi, GLib, JSON-GLib, V8, etc. – is how I've been maintaining Frida's patches on top of the various upstream components that we need minor tweaks for. It's also where fixes are staged until they've gone through some testing so I feel comfortable submitting them upstream.

Due to us having to maintain significant changes to GLib, to make it support cleaning up static allocations and keeping track of resources (threads, file-descriptors, etc.), and GLib upstream not considering Frida's use-case a valid use-case, we also end up having to maintain a few minor patches to the Vala compiler.

I'm hoping to find some time soon to rebase patches and get around to submitting the fixes. (Which I've been meaning to do earlier this year but have been spread too thin unfortunately.)

**Comment by ricotz** [comment]
@oleavr Thanks for explaining! I am looking forward to take a look at these patches. Please do a real `git rebase` on the upstream branch of your choice.

**Comment by oleavr** [comment]
@ricotz Awesome! Will do 🙌

**Comment by ricotz** [comment]
@oleavr Hey :slightly_smiling_face: , any progress here?

**Comment by oleavr** [comment]
@ricotz Hi! 🙂 Sorry for the delay here. Just opened two MRs that cover the remaining bits:
https://gitlab.gnome.org/GNOME/vala/merge_requests/102
https://gitlab.gnome.org/GNOME/vala/merge_requests/103
(The remainder of the patches are specific to our GLib fork, so we're now down to just two MRs 🎉)
